nname: Auto Commit and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  repository_dispatch:
    types:
      - chatgpt-trigger

# 1. הרשאת write ל-GITHUB_TOKEN
permissions:
  contents: write

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      # 2. Checkout עם PAT ושמירת credentials
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          persist-credentials: true

      # 3. יצירת/עדכון הקובץ
      - name: Generate or update code
        run: |
          echo "# Generated at $(date)" >> example.txt

      # 4. קביעת נתוני Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 5. Commit & Push
      - name: Commit & Push changes
        run: |
          git add .
          git diff --quiet || git commit -m "Automated update by CI"
          git push origin HEAD:main
